### ISSUE TITLE
Secret Manager Pre-Launch Checklist

### ISSUE THREAD

**Issue by blowmage** [googleapis/gapic-generator-ruby#299]
Here are the things that need to happen before we release a gem generated from the microgenerator. Please add to this list as things are discovered.

- [x] Release google-cloud-errors 1.0
- [x] Update google-cloud-core to depend on google-cloud-errors 1.0
- [x] Release google-cloud-core 1.5
- [x] Update gapic-generator-cloud gemspec template and add google-cloud-errors `~> 1.0` dependency
- [x] Update gapic-common dev dependency on google-cloud-core `~> 1.5`
- [x] Release gapic-common 0.1
- [x] Update all `gemspec.erb` templates to set gapic-common dependency to `~> 0.1.0`
- [x] Remove gapic-common from `gemfile.erb` all template files
- [x] Update `secret_manager` pull request branches with latest generated files with  updated dependencies
- [x] Release google-cloud-secret_manager-v1beta1
- [x] Release google-cloud-secret_manager
- [ ] Add google-cloud-secret_manager to google-cloud, updating many, many Gemfiles
- [ ] Release google-cloud

**Comment by dazuma** [comment]
> Update gapic-common to depend on google-cloud-errors `~> 1.0`

@blowmage I thought the error translation to `Google::Cloud::Error` was cloud-specific?

**Comment by blowmage** [comment]
Yes, it is. We don’t need a runtime dependency. The cloud generator should add that dependency on the cloud’s gemspec template.

**Comment by blowmage** [comment]
Updated the checklist

**Comment by quartzmo** [comment]
Please add migration guide for an existing gem when adapting this list for other services.

**Comment by blowmage** [comment]
Migration Guide is added to #306.

**Comment by dazuma** [comment]
We're not adding microgenerator libraries to google-cloud, so disregarding the last two items. Closing.
