### ISSUE TITLE
Language Pre-Launch Checklist

### ISSUE THREAD

**Issue by blowmage** [googleapis/gapic-generator-ruby#306]
This assumes that google-cloud-secret_manager has already been released, and the items in #299 have all been completed.

- [ ] Update googleapis/google-cloud-ruby#4540 with the latest generated files, including updated dependencies
- [ ] Approve and merge googleapis/google-cloud-ruby#4540
- [ ] Author Migration Guide for this transition
- [ ] Link to Migration Guide URL in google-cloud-language post-install message
- [ ] Release google-cloud-language-v1
- [ ] Release google-cloud-language-v1beta1
- [ ] Release google-cloud-language-v1beta2
- [ ] Release google-cloud-language

**Comment by dazuma** [comment]
obsoleting this.
